name: Etapa 5 - Deploy Ambientes
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - run: echo "Deploy no ambiente DEV"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - run: echo "Deploy no ambiente PROD"