name: Etapa 2 - Variáveis e Secrets
on: [push, workflow_dispatch]

jobs:
  mostrar-vars-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Exibir Variáveis de Configuração
        run: |
          echo "Modo da Aplicação: ${{ vars.APP_MODE }}"
          echo "Email de Suporte: ${{ vars.SUPPORT_EMAIL }}"

      - name: Utilizar Secret de Produção
        run: |
          # O GitHub vai mascarar esse valor nos logs com ***
          echo "Autenticando com o token: ${{ secrets.PROD_TOKEN }}"